# Numpy Notes

In [2]:
import numpy as np
a = np.arange(1, 10, 2) #start, end (exclusive), step
a = np.arange(10, dtype='float64') # array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

print(np.arange(10)) # [0 1 2 3 4 5 6 7 8 9]
a.ndim #gives x in x X y matrix
a.shape #gives [x,y] in x X y matrix

a = np.linspace(0, 1, 8) #array([0.,0.14285714,0.28571429,0.42857143,0.57142857,0.71428571,0.85714286,1.])

a = np.ones((2,3)) #array([[1.,1.,1.],[1.,1.,1.]])
a = np.zeros((2,3)) #array([[0.,0.,0.],[0.,0.,0.]])

a = np.eye(3) #array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
a = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

a = np.random.rand(4) # array([0.7663811 , 0.79018053, 0.48939364, 0.01307068])
a = np.random.randn(4) # array([-0.32830012,  0.52506368, -1.51810411, -2.31168318])
a = np.random.randint(0, 20, 15) # array([13,  9,  7,  6,  5,  4,  3,  2,  1,  0,  0,  0,  0,  0,  0])

a[[2, 3, 2, 4, 2]] #Gives values of index 2, 3, 2, 4, 2 simuntaneously.
a[5:] = 10 #array([0.,0.,0.,0.,0.,10.,10.,10.])
b = np.arange(15) # and
# a[5:] = b[::-1] #array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

np.array_equal(a, b) #Checks if two arrays are equal
np.shares_memory(a, b) #Determine if two arrays share memory. If true then if we modify one, the other will be modified as well.
# To avoid this we can use copy()
# c = a[::2].copy()

np.logical_or(a, b) #Returns an array of booleans where True if either of the inputs is True.
np.logical_and(a, b) #Returns an array of booleans where True if both of the inputs are True.

np.sin(a) #Returns the sine of each element of a.
np.log(a) #Returns the natural logarithm of each element of a.
np.exp(a) #Returns the exponential of each element of a.

np.array([[1, 1], [2, 2]]).sum(axis=0) #Sum of each column
np.array([[1, 1], [2, 2]]).sum(axis=1) #Sum of each row

np.array([1, 3, 2]).min() #Returns the minimum value of an array.
np.array([1, 3, 2]).max() #Returns the maximum value of an array.
np.array([1, 3, 2]).mean() #Returns the mean value of an array.
np.array([1, 3, 2]).std() #Returns the standard deviation of an array.
np.array([1, 3, 2]).var() #Returns the variance of an array.
np.array([1, 3, 2]).argmax() #Returns the indices of the maximum values along an axis.
np.array([1, 3, 2]).argmin() #Returns the indices of the minimum values along an axis.

np.all(a) #Returns True if all elements of a are True.
np.any(a) #Returns True if any of the elements of a are True.

[0 1 2 3 4 5 6 7 8 9]


True

## To check time for a code
### Use "%time it"

In [3]:
L = range(1000)
%timeit [i**2 for i in L]

475 µs ± 55.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Fancy Indexing/Masking

In [4]:
a = np.random.randint(0, 20, 15)
mask = (a % 2 == 0)
extract_from_a = a[mask] #array([18, 18,  0, 14, 12,  4, 16,  8])
a[mask] = -1 #array([-1, 17,  1, -1,  5, 17, -1, -1, -1, 11, -1, 15, -1, -1,  7])

## Extracting text from files

### data = np.loadtxt('populations.txt')
array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

### populations.std(axis=0)
array([ 20897.90645809,  16254.59153691,   3322.50622558])

### np.argmax(populations, axis=1)
array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

## Broad casting

In [5]:
a = np.tile(np.arange(0, 40, 10), (3,1)) #Makes a 1 X 3 matrix with values 0, 10, 20, 30 in a tile of 3 X 1 dimension where the matrix occupies 1 unit
a=a.T # Transpose the array

a = np.arange(0, 40, 10)
a = a[:, np.newaxis]  # adds a new axis -> 2D array

## Array Shape Manipulation

In [6]:
a.ravel() #Returns a flattened array. A 1D array with all the elements of a.

z = np.array([1, 2, 3])
z[:, np.newaxis] # Used to increase the dimension of the exist by 1 --> 2D will become 3D array.

array([[1],
       [2],
       [3]])